// https://school.programmers.co.kr/learn/courses/30/lessons/17684

function solution(msg) {
  const answer = [];
  let str = msg;

  const dic = Array.from({ length: 27 }, (v, i) => String.fromCharCode(i + 64));
  let maxWordLen = 1;
  let len = 1;

  while (str.length > 0) {
    const sliceWord = str.substr(0, len);

    const idx = dic.indexOf(sliceWord);

    if (idx === -1) {
      len -= 1;
      continue;
    } else {
      answer.push(idx);
      const addWord = str.substr(0, len + 1);
      if (str.length !== len) dic.push(addWord);
      len += 1;
      str = str.substr(len - 1, str.length);
      maxWordLen = Math.max(addWord.length, maxWordLen);
      len = maxWordLen;
    }
  }

  return answer;
}

// const tc = 'KAKAO';
const tc = 'TOBEORNOTTOBEORTOBEORNOT';
// const tc = 'ABABABABABABABAB';
// const tc =
// eslint-disable-next-line max-len
// 'THATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITIS';

console.log(solution(tc));
